# Docker Compose configuration for Driver Drowsiness Detection System
# Provides easy deployment with camera access and port mapping

version: '3.8'

services:
  drowsiness-detector:
    build: .
    container_name: driver_drowsiness_detector
    ports:
      - "5000:5000"
    devices:
      - /dev/video0:/dev/video0  # Map camera device (Linux)
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # For GUI access if needed
    environment:
      - DISPLAY=${DISPLAY}
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
    # For better camera access on different systems
    privileged: true
    
    # Network mode for better performance
    # network_mode: "host"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

# Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - drowsiness-detector
  #   restart: unless-stopped